// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnSRswU4dNtWNDw6k6P7IhvonyeQCibk',
    appId: '1:250773787739:web:438db28c92f3a769ff9b7e',
    messagingSenderId: '250773787739',
    projectId: 'task-management-88635',
    authDomain: 'task-management-88635.firebaseapp.com',
    storageBucket: 'task-management-88635.firebasestorage.app',
    measurementId: 'G-3H8KQ6XGZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6YKRcyelZN3c-MmiqYJXFRTrpKDli13k',
    appId: '1:250773787739:android:9c9ad169aac7238aff9b7e',
    messagingSenderId: '250773787739',
    projectId: 'task-management-88635',
    storageBucket: 'task-management-88635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwOYd4f-8JypsGrQrJweSsVdPohIUqx8',
    appId: '1:250773787739:ios:0c0b9b26543f4938ff9b7e',
    messagingSenderId: '250773787739',
    projectId: 'task-management-88635',
    storageBucket: 'task-management-88635.firebasestorage.app',
    iosBundleId: 'com.developersHub.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwOYd4f-8JypsGrQrJweSsVdPohIUqx8',
    appId: '1:250773787739:ios:0c0b9b26543f4938ff9b7e',
    messagingSenderId: '250773787739',
    projectId: 'task-management-88635',
    storageBucket: 'task-management-88635.firebasestorage.app',
    iosBundleId: 'com.developersHub.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdnSRswU4dNtWNDw6k6P7IhvonyeQCibk',
    appId: '1:250773787739:web:f8d18c2ff584495cff9b7e',
    messagingSenderId: '250773787739',
    projectId: 'task-management-88635',
    authDomain: 'task-management-88635.firebaseapp.com',
    storageBucket: 'task-management-88635.firebasestorage.app',
    measurementId: 'G-ZJFERZNZ67',
  );
}
